### ISSUE TITLE
Select Calendar where to add events to

### ISSUE THREAD

**Issue by rohansaw** [kalle-app/kalle#113]
**Is your feature request related to a problem? Please describe.**
User has multiple calendars connected. In which should a booked event be added to

**Describe the solution you'd like**
- set a default calendar in settings
- When creating a meeting be able to set a calendar where the event will be added

**Comment by sspangenberg** [comment]
In addition we have to add Cascade Deletion of meetings in the case the assigned calendar is going to be deleted.
