### ISSUE TITLE
Design bug: gigantic buttons in meeting/create

### ISSUE THREAD

**Issue by phlprcks** [kalle-app/kalle#158]
**Describe the bug**
See the attached picture of malformed buttons

**To Reproduce**

1. Go to dashboard (logged in)
2. Create new Meeting
3. Wait to be redirected to Meeting overview
4. Click to create new Meeting
5. see malformed buttons (also happens if clicked on +Meeting in the Dashboard)

Reloading the page makes the appereance normal again. I suspect its some weird caching.

![image](https://user-images.githubusercontent.com/33530575/107760560-3e86ae80-6d2a-11eb-87c2-a918854902ec.png)

**Comment by Skn0tt** [comment]
reminds me of a tile covered in propulsion gel
![](https://media.giphy.com/media/wb66DZmu3hlMA/giphy.gif)
