### ISSUE TITLE
Validate Schedule Input

### ISSUE THREAD

**Issue by phlprcks** [kalle-app/kalle#164]
**Describe the bug**
The times added in "Add Schedule" are not validated whatsoever

**To Reproduce**

1. Go to /schedules
2. Click on Add Schedule
3. Insert a random number e.g. 123456 or a string e.g. "the answer is 42" instead of 9:00
4. Click Save Schedule, see it is added

**Comment by sspangenberg** [comment]
Solved by the pull request linked to issue #77
