### ISSUE TITLE
Add back buttons (to previous page)

### ISSUE THREAD

**Issue by rohansaw** [kalle-app/kalle#173]
Currently it is quite annoying to navigate between pages of the application. A much better user experience would be to add buttons to get back to to the previous page on subpages.

I think with the react router history this should be quite easy

**Comment by phlprcks** [comment]
@rohansaw do you mean like breadcrumbs on each page? Because we have like 4-5 pages so I'm not sure this really makes sense since people could easily use the Browser navigation.
In the steppers (e.g. for creating a meeting) we already offer a back button...

**Comment by rohansaw** [comment]
Jup meant somethink like that. I actually think this would improve the usability quite a bit, I already was a few times in the situation where such a button would have come in handy. And making the user need to user the browser navigation is not so nice imo

**Comment by sspangenberg** [comment]
I don't know whether this is really needed and in addition it could make the design worse. E.g. at this site you also have to use the browser navigation to go back to the issues overview...
