### ISSUE TITLE
Fix scheduling algorithm

### ISSUE THREAD

**Issue by sspangenberg** [kalle-app/kalle#184]
The scheduling algorithm does not work correctly under specific circumstances (see picture)
This occurs if the remaining days of the month are blocked by the specified schedule and thus the next available day is the first of the next month. Then in addition to the wrong times the days in the next month are not available although they should be.
![cypress-screenshot](https://user-images.githubusercontent.com/49531479/109385943-a119a600-78f7-11eb-916a-f8c7b527ea5a.png)

**Comment by phlprcks** [comment]
@sspangenberg I tried several different schedules/meetings but could not reproduce this specific issue. Are you sure it is a problem with the application itself or might the problem be caused by some behavior in the cypress tests? I could imagine that there might arise problems when checking for "contains 1" as there is are several ones in the DOM

![image](https://user-images.githubusercontent.com/33530575/110037582-e9ddbe80-7d3e-11eb-854d-4ef947a92199.png)

**Comment by phlprcks** [comment]
Also I could not reproduce the issue with the unwanted odd time slots. I used several meeting durations but all worked fine. Do you have any idea what triggered this bug? My only explanation would be that there was a blocked schedule in one of the connected calendars, so every meeting after that would be shifted x minutes.
![image](https://user-images.githubusercontent.com/33530575/110039401-725d5e80-7d41-11eb-9715-80ec79ca38e5.png)

**Comment by sspangenberg** [comment]
> 
> 
> @sspangenberg I tried several different schedules/meetings but could not reproduce this specific issue. Are you sure it is a problem with the application itself or might the problem be caused by some behavior in the cypress tests? I could imagine that there might arise problems when checking for "contains 1" as there is are several ones in the DOM
> 
> ![image](https://user-images.githubusercontent.com/33530575/110037582-e9ddbe80-7d3e-11eb-854d-4ef947a92199.png)

It's a bug with the application itself because I also had this problem outside of the tests. Currently we are not checking whether it contains 1 but 15 and 15 only appears one time in every case because it is in the middle of the month. I have adjusted the test in that way to migitate the multiple 1 problem.

**Comment by sspangenberg** [comment]
> 
> 
> Also I could not reproduce the issue with the unwanted odd time slots. I used several meeting durations but all worked fine. Do you have any idea what triggered this bug? My only explanation would be that there was a blocked schedule in one of the connected calendars, so every meeting after that would be shifted x minutes (as example I had a 11 min. long meeting at 2pm.
> ![image](https://user-images.githubusercontent.com/33530575/110039401-725d5e80-7d41-11eb-9715-80ec79ca38e5.png)

I doubt that this could be the reason because I used the nearly empty test calendar and this problem appears local and in the CI. For the specific circumstances please take a look at the issue description.

**Comment by sspangenberg** [comment]
If you choose a timespan for the meeting today from 5.3. to e.g. 12.3. with the dault schedule then you receive the following result. The days in the next week like 8.3. should not be blocked.
 
![grafik](https://user-images.githubusercontent.com/49531479/110124127-05d67400-7dc2-11eb-87ce-0e18dc9967cb.png)
