### ISSUE TITLE
Use Timezones

### ISSUE THREAD

**Issue by rohansaw** [kalle-app/kalle#81]
**Is your feature request related to a problem? Please describe.**
As Kalle users can be in different timezones we need to take this into consideration.

**Describe the solution you'd like**
Save time in normalized format, add then maybe add timzones for users ? Dunno exactly, need to think this through
Also take into consideration where an invitee is currently based?

**Comment by sspangenberg** [comment]
We should store and calculate every time internal in UTC and only convert it at display or for calendar entries. E.g. we could let the user specify his timezone at signup. Also we should check the timezones of the connected calendars, so that every appointment matches the specified intervals.
