### ISSUE TITLE
Usage of hardcoded localhost

### ISSUE THREAD

**Issue by Lasklu** [kalle-app/kalle#99]
**Describe the bug**
We use multiple times a hardcoded "localhost:3000". This might break if we deploy it or another port is used.

**Expected behavior**
The user should not see bugs caused by this behaviour. We should propose env-variables where the host can be provided.

**Comment by Lasklu** [comment]
@Skn0tt rohan meinte, dass du schon was in die richtung gemacht hast?

**Comment by Skn0tt** [comment]
I guess he mean this: https://github.com/kalle-app/kalle/blob/f970f490d1f9802d409fbe8aed7beac306f06e4b/app/meetings/components/Meetings.tsx#L26

**Comment by Lasklu** [comment]
what do you think of using an env variable? If we will to provide a self-hosted version, a hard coded "kalle.app" might break, too...
https://github.com/kalle-app/kalle/blob/f970f490d1f9802d409fbe8aed7beac306f06e4b/app/meetings/components/Meetings.tsx#L10

**Comment by Skn0tt** [comment]
In this specific case, it doesn't matter. `https://kalle.app` is only used as a fallback for when there's no `location` (during server-side-rendering). Once it's hydrated on the client, it will use the correct origin.

Using an env variable is still a good idea, e.g. for usage in email templates.
